# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    v1.docs.serverless.com
#
# Happy Coding!

service: iopipe-workshop-doge-1 # NOTE: update this with your service name

provider:
  name: aws
  region: us-east-1
  runtime: nodejs4.3
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "s3:ListBucket"
         Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "iopipe-workshop-doge-1"} ] ] }
      -  Effect: "Allow"
         Action:
           - "s3:PutObject"
         Resource:
           Fn::Join:
             - ""
             - - "arn:aws:s3:::"
               - "Ref" : "iopipe-workshop-doge-1"

#package:
#  include:
#   - functions

functions:
  create:
    handler: doge.create
    memorySize: 128
    timeout: 30
    events:
      - http:
          path: doge/create
          method: get

#   you can add any of the following events
#   events:
#     - http:
#         path: users/create
#         method: get
#     - s3: ${bucket}
#     - schedule: rate(10 minutes)
#     - sns: greeter-topic

# you can add CloudFormation resource templates here
resources:
  Resources:
    newResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: iopipe-workshop-doge-1
